// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CzsAGWhVtBIORAIdkrrapw1XV-hoGms',
    appId: '1:779144812985:web:2c55236ffbf49f02b27e68',
    messagingSenderId: '779144812985',
    projectId: 'umaps-7c519',
    authDomain: 'umaps-7c519.firebaseapp.com',
    storageBucket: 'umaps-7c519.appspot.com',
    measurementId: 'G-MR46LB8B1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaynq2qoRYzVSWxtpYv84MapB1BiaHr4',
    appId: '1:779144812985:android:8d092b26f0842337b27e68',
    messagingSenderId: '779144812985',
    projectId: 'umaps-7c519',
    storageBucket: 'umaps-7c519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzGiLQFPL5uTUZQCVP_gwiKsq8KmnHjQc',
    appId: '1:779144812985:ios:cf4b63d40a9b158bb27e68',
    messagingSenderId: '779144812985',
    projectId: 'umaps-7c519',
    storageBucket: 'umaps-7c519.appspot.com',
    iosClientId: '779144812985-qrucuqsj2s2io1hevuillc7run1e90ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.umapsbyarasaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzGiLQFPL5uTUZQCVP_gwiKsq8KmnHjQc',
    appId: '1:779144812985:ios:cf4b63d40a9b158bb27e68',
    messagingSenderId: '779144812985',
    projectId: 'umaps-7c519',
    storageBucket: 'umaps-7c519.appspot.com',
    iosClientId: '779144812985-qrucuqsj2s2io1hevuillc7run1e90ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.umapsbyarasaka',
  );
}
